version : '3' # 3이 안정적임.

services:
  nginx:
    container_name: c_nginx
    build: ./requirements/nginx/
    image: nginx
    depends_on :
      - wordpress
    restart: always # 문제가 생길 경우 항상 재실행
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wp_volume:/var/www/

  wordpress: # 9000으로 포트 연결 시켜줄 필요는 없는가?
    container_name: c_wordpress
    build: ./requirements/wordpress/
    image: wordpress
    depends_on :
      - mariadb
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/

  mariadb:
    container_name: c_mariadb
    build: ./requirements/mariadb/
    image: mariadb
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql/

networks:
  inception_network:

volumes:
    db_volume:
      driver_opts:
        type: volume
        o : 'bind'
        device: '/home/dohykim/data/database'

    wp_volume:
      driver_opts:
        type: volume
        o : 'bind'
        device: '/home/dohykim/data/wordpress'

